var Q=Object.create;var b=Object.defineProperty;var W=Object.getOwnPropertyDescriptor;var Y=Object.getOwnPropertyNames;var j=Object.getPrototypeOf,ee=Object.prototype.hasOwnProperty;var C=c=>b(c,"__esModule",{value:!0});var te=(c,t)=>{C(c);for(var e in t)b(c,e,{get:t[e],enumerable:!0})},re=(c,t,e)=>{if(t&&typeof t=="object"||typeof t=="function")for(let r of Y(t))!ee.call(c,r)&&r!=="default"&&b(c,r,{get:()=>t[r],enumerable:!(e=W(t,r))||e.enumerable});return c},v=c=>re(C(b(c!=null?Q(j(c)):{},"default",c&&c.__esModule&&"default"in c?{get:()=>c.default,enumerable:!0}:{value:c,enumerable:!0})),c);te(exports,{default:()=>O,hmrAdder:()=>k});var w=typeof document=="undefined"?new(require("url")).URL("file:"+__filename).href:document.currentScript&&document.currentScript.src||new URL("main.js",document.baseURI).href;var B=v(require("acorn"));var F=class{constructor(){this.UPDATE_LISTENER_FUNC_NAME="_bjsx_hmr_update";this.PARAM_ALTER_NAME="_blue_insert_params"}transform(t){}getImports(...t){return[]}getExports(...t){return[]}getDependentJSXComponents(t,e){return[]}getFunctions(t){return[]}getVars(t,e){return[]}fromDirectReturnToVarReturn(t){return""}getReturnValue(t){return""}getInsertRecord(){return[]}replaceCode(t,e,r,n,s=!1){let o=0;return n.filter(a=>a[0]<e[0]||s&&a[0]===e[0]).forEach(a=>o+=a[1]),n.push([e[0],t.length-e[1]+e[0]]),r.substring(0,e[0]+o)+t+r.substring(e[1]+o)}insertCode(t,e,r,n,s=!1){return this.replaceCode(t,[e,e],r,n,s)}getCodeFragment(t,e,r){let n=t[0],s=t[1];for(let o=r.length;o--;){let[a,m]=r[o];a<t[1]&&(s+=m,a<t[0]&&(n+=m))}return e.substring(n,s)}};var D=v(require("path")),P=v(require("fs")),M=class extends F{constructor(){super();this.Parser=B.Parser}transform(t,e){t=t.replace(/=>/g,"=> ");let r=this.Parser.parse(t,{ecmaVersion:"latest",sourceType:"module"}),n=t,s=this.getImports(r.body,e),o=this.getExportedFunctions(r.body),a=this.getInsertRecord();return o.forEach(m=>{let{start:g,end:h}=m,E=this.getCodeFragment([g,h],t,a),u=this.getDependentJSXComponents(E,s);t=this.replaceCode(this.processFunctionCode(u,m,E,n),[g,h],t,a)}),t}addHotListenerInfo(t,e,r,n){var o,a;(a=t[o=e.info.src])!=null||(t[o]={varMapCode:"",listenCode:""});let s=t[e.info.src];s.varMapCode+=`${e.info.imports[e.name]}:${e.name},`,s.listenCode+=`
if(${r}.${e.refName}.${this.UPDATE_LISTENER_FUNC_NAME}){
  ${r}.${e.refName}=${r}.${e.refName}.${this.UPDATE_LISTENER_FUNC_NAME}(${e.name});
  ${n}
}else{
  import.meta.hot.decline()
}
`}processFunctionCode(t,e,r,n){var V,H,J,X;let s=this.getInsertRecord(),o=r,a=e.body,m=a.start-e.start,g=a.end-e.start,h=a.body,E=e.params[0],u="";if(E){let i=E.start-e.start,l=E.end-e.start,y=r.substring(i,l);r=this.replaceCode(this.PARAM_ALTER_NAME,[i,l],r,s),u=`
let ${y}=${this.PARAM_ALTER_NAME};`}let d="self",S=[],I={},p,U=0,f=h==null?void 0:h.find(i=>i.type==="ReturnStatement"),R=a.type==="CallExpression"&&((H=(V=a.callee)==null?void 0:V.object)==null?void 0:H.name)==="Blue";if(f)f.argument.type==="Identifier"&&(d=f.argument.name);else if(!R)return o;let q=f&&f.argument.type==="CallExpression"&&((X=(J=f.argument.callee)==null?void 0:J.object)==null?void 0:X.name)==="Blue",z=R?g:f.start-e.start;[...r.matchAll(/Blue\.r\(/g)].forEach(i=>{var y,N;let l=this.Parser.parseExpressionAt(r,i.index,{ecmaVersion:"latest",sourceType:"module"});l.type==="SequenceExpression"&&(l=l.expressions.find(x=>x.start===l.start)),(l==null?void 0:l.type)==="CallExpression"&&((y=l==null?void 0:l.arguments[1])==null?void 0:y.type)==="ObjectExpression"&&(p!=null||(p=(N=l.arguments[1].properties.find(x=>{var A;return((A=x.key)==null?void 0:A.name)==="ref"}))==null?void 0:N.value.elements[0].name))}),t.forEach(i=>{let l=i.node.arguments[1];if(l.type==="ObjectExpression"){let y=l.properties.find(N=>N.key.name==="ref");if(y){let N="",x=y.value.elements;i.refName=x[1].value,i.hasRef=!0,R||(h.forEach(({type:A,start:_,end:Z})=>{let L=_-e.start,G=Z-e.start,K=o.substring(L,G);A==="ExpressionStatement"&&o.indexOf(i.refName,L)===L&&(N+=`${p}.${K};`)}),[...o.matchAll(new RegExp(i.refName,"g"))].forEach(A=>{try{let _=this.Parser.parseExpressionAt(o,A.index,{ecmaVersion:"latest",sourceType:"module"});(_.type==="AssignmentExpression"||_.type==="CallExpression")&&(r=this.insertCode(`${p}.`,A.index,r,s))}catch{}})),this.addHotListenerInfo(I,i,p,N)}else i.refName=`bjsxc_${U++}`,i.hasRef=!1,S.push(()=>{r=this.insertCode(`ref:[${p},'${i.refName}'],`,l.start+1,r,s),this.addHotListenerInfo(I,i,p,"")})}else i.refName=`bjsxc_${U++}`,S.push(()=>{r=this.replaceCode(`{ref:[${p},'${i.refName}']}`,[l.start,l.start+4],r,s),this.addHotListenerInfo(I,i,p,"")})}),p||(p="refs",u+=`const ${p}={};`);for(let i=S.length;i--;)S[i]();if(R)u=`{${u}const ${d}=`,r=this.insertCode(`
return ${d};}`,a.end,r,s,!0);else if(q){let i=this.getCodeFragment([f.start-e.start+6,f.end-e.start],r,s);u=`${u}
      const ${d}=${i};`,r=this.replaceCode(`
return ${d};`,[f.start-e.start,f.start-e.start+i.length+7],r,s)}r=this.insertCode(u,R?m:m+1,r,s);let $="";E?$=`
${d}.${this.UPDATE_LISTENER_FUNC_NAME} = (Comp) =>{
  const newElem=Comp(${this.PARAM_ALTER_NAME});
  ${d}.before(newElem);
  ${d}.remove();
  return newElem
}
`:$=`
${d}.${this.UPDATE_LISTENER_FUNC_NAME} = (Comp) =>{
  const newElem=Comp();
  ${d}.before(newElem);
  ${d}.remove();
  return newElem
}
`;let T=!1;for(let i in I){T||(T=!0);let l=I[i];$+=`import.meta.hot.accept('${i}',({${l.varMapCode}})=>{${l.listenCode}});`}return T&&($=`
if(import.meta.hot){
  ${$}
}else{
  console.warn('import.meta.hot not exist')
}
`),r=this.insertCode($,z,r,s),r}resolveFilePath(t,e){let r=D.default.resolve(e,"../",t);try{let n=P.default.statSync(r);if(n.isDirectory()){let s=P.default.readdirSync(r);for(let o=s.length;o--;){let a=s[o];if(/index\.[jt]sx$/.test(a))return t+"/"+a}}else return n.isFile()?t:!1}catch{let s=P.default.readdirSync(D.default.resolve(r,"../")),o=D.default.basename(t),a=D.default.dirname(t);for(let m=s.length;m--;){let g=s[m];if(s.indexOf(o)===0&&/\.[jt]sx$/.test(g))return a+"/"+g}}return!1}getImports(t,e){let r={varNames:[],info:{}};return t.forEach(n=>{if(n.type!=="ImportDeclaration"||n.source.value.indexOf(".")!==0)return 0;let s=this.resolveFilePath(n.source.value,e);if(!s)return 0;let o={src:s,imports:{}};r.info[n.source.value]=o,n.specifiers.forEach(a=>{let m=a.local.name;a.type==="ImportDefaultSpecifier"?o.imports[m]="default":a.type==="ImportSpecifier"&&(o.imports[m]=a.imported.name),r.varNames.push({name:m,info:o})})}),r}getExports(t){return t.filter(e=>e.type==="ExportDefaultDeclaration"||e.type==="ExportNamedDeclaration")}getExportedFunctions(t){let e=[],r=n=>{n.type==="FunctionDeclaration"||n.type==="ArrowFunctionExpression"?e.push(n):n.type==="VariableDeclaration"&&n.declarations.forEach(s=>r(s.init))};return t.forEach(n=>{if(n.type==="ExportDefaultDeclaration"||n.type==="ExportNamedDeclaration"){let{declaration:s}=n;s&&r(s)}}),e}getDependentJSXComponents(t,e){let r=[];return[...t.matchAll(/Blue\.r\(([A-Z][A-z_]*)/g)].forEach(n=>{let s=n[1],o=this.Parser.parseExpressionAt(t,n.index,{ecmaVersion:"latest",sourceType:"module"});o.type==="SequenceExpression"&&(o=o.expressions.find(a=>a.start===o.start)),e.varNames.forEach(a=>{if(a.name===s){let m={name:s,info:a.info,node:o,index:n.index};r.push(m)}})}),r}getVars(t,e){return[]}fromDirectReturnToVarReturn(t){return""}getReturnValue(t){return""}};var k=new M;function O({enabled:c}={enabled:!0}){return{name:"vite-plugin-blue-hmr",apply(t,{command:e}){return c&&e==="serve"},transform(t,e){if(!e.includes("node_modules")&&/\.[jt]sx$/.test(e))return k.transform(t,e)}}}0&&(module.exports={hmrAdder});
