import{Parser as j}from"acorn";var D=class{constructor(){this.UPDATE_LISTENER_FUNC_NAME="_bjsx_hmr_update";this.PARAM_ALTER_NAME="_blue_insert_params"}transform(t){}getImports(...t){return[]}getExports(...t){return[]}getDependentJSXComponents(t,e){return[]}getFunctions(t){return[]}getVars(t,e){return[]}fromDirectReturnToVarReturn(t){return""}getReturnValue(t){return""}getInsertRecord(){return[]}replaceCode(t,e,r,i,s=!1){let o=0;return i.filter(n=>n[0]<e[0]||s&&n[0]===e[0]).forEach(n=>o+=n[1]),i.push([e[0],t.length-e[1]+e[0]]),r.substring(0,e[0]+o)+t+r.substring(e[1]+o)}insertCode(t,e,r,i,s=!1){return this.replaceCode(t,[e,e],r,i,s)}getCodeFragment(t,e,r){let i=t[0],s=t[1];for(let o=r.length;o--;){let[n,c]=r[o];n<t[1]&&(s+=c,n<t[0]&&(i+=c))}return e.substring(i,s)}};import _ from"path";import C from"fs";var v=class extends D{constructor(){super();this.Parser=j}transform(t,e){t=t.replace(/=>/g,"=> ");let r=this.Parser.parse(t,{ecmaVersion:"latest",sourceType:"module"}),i=t,s=this.getImports(r.body,e),o=this.getExportedFunctions(r.body),n=this.getInsertRecord();for(let c of o){let{start:d,end:y}=c,N=this.getCodeFragment([d,y],t,n),f=this.getDependentJSXComponents(N,s);t=this.replaceCode(this.processFunctionCode(f,c,N,i),[d,y],t,n)}return t}addHotListenerInfo(t,e,r,i){var o,n;(n=t[o=e.info.src])!=null||(t[o]={varMapCode:"",listenCode:""});let s=t[e.info.src];s.varMapCode+=`${e.info.imports[e.name]}:${e.name},`,s.listenCode+=`
if(${r}.${e.refName}.${this.UPDATE_LISTENER_FUNC_NAME}){
  ${r}.${e.refName}=${r}.${e.refName}.${this.UPDATE_LISTENER_FUNC_NAME}(${e.name}, ${e.attrObjCode?e.attrObjCode:"null"});
  ${i}
}else{
  import.meta.hot.decline()
}
`}processFunctionCode(t,e,r,i){var T,L,V,w,B,H;let s=this.getInsertRecord(),o=r,n=e.body,c=n.start-e.start,d=n.end-e.start,y=n.body,N=e.params[0],f="";if(N){let a=N.start-e.start,l=N.end-e.start,u=r.substring(a,l);r=this.replaceCode(this.PARAM_ALTER_NAME,[a,l],r,s),f=`
let ${u}=${this.PARAM_ALTER_NAME};`}let g="self",I=[],x={},p,M=0,m=y==null?void 0:y.find(a=>a.type==="ReturnStatement"),A=n.type==="CallExpression"&&((L=(T=n.callee)==null?void 0:T.object)==null?void 0:L.name)==="Blue";if(m)m.argument.type==="Identifier"&&(g=m.argument.name);else if(!A)return o;let J=m&&m.argument.type==="CallExpression"&&((w=(V=m.argument.callee)==null?void 0:V.object)==null?void 0:w.name)==="Blue",O=A?d:m.start-e.start;for(let a of r.matchAll(/Blue\.r\(/g)){let l=this.Parser.parseExpressionAt(r,a.index,{ecmaVersion:"latest",sourceType:"module"});if(l.type==="SequenceExpression"&&(l=l.expressions.find(u=>u.start===l.start)),(l==null?void 0:l.type)==="CallExpression"&&((B=l==null?void 0:l.arguments[1])==null?void 0:B.type)==="ObjectExpression"){let u=(H=l.arguments[1].properties.find(E=>{var R;return((R=E.key)==null?void 0:R.name)==="ref"}))==null?void 0:H.value.elements[0].name;if(u){p=u;break}}}for(let a of t){let l=a.node.arguments[1];if(l.type==="ObjectExpression"){a.attrObjCode=o.substring(l.start,l.end);let u=l.properties.find(E=>E.key.name==="ref");if(u){let E="",R=u.value.elements;if(a.refName=R[1].value,a.hasRef=!0,!A){for(let{type:b,start:$,end:X}of y){let P=$-e.start,U=X-e.start,k=o.substring(P,U);b==="ExpressionStatement"&&o.indexOf(a.refName,P)===P&&(E+=`${p}.${k};`)}for(let b of o.matchAll(new RegExp(a.refName,"g")))try{let $=this.Parser.parseExpressionAt(o,b.index,{ecmaVersion:"latest",sourceType:"module"});($.type==="AssignmentExpression"||$.type==="CallExpression")&&(r=this.insertCode(`${p}.`,b.index,r,s))}catch{}}this.addHotListenerInfo(x,a,p,E)}else a.refName=`bjsxc_${M++}`,a.hasRef=!1,I.push(()=>{r=this.insertCode(`ref:[${p},'${a.refName}'],`,l.start+1,r,s),this.addHotListenerInfo(x,a,p,"")})}else a.refName=`bjsxc_${M++}`,I.push(()=>{r=this.replaceCode(`{ref:[${p},'${a.refName}']}`,[l.start,l.start+4],r,s),this.addHotListenerInfo(x,a,p,"")})}p||(p="refs",f+=`const ${p}={};`);for(let a=I.length;a--;)I[a]();if(A)f=`{${f}const ${g}=`,r=this.insertCode(`
return ${g};}`,n.end,r,s,!0);else if(J){let a=this.getCodeFragment([m.start-e.start+6,m.end-e.start],r,s);f=`${f}
      const ${g}=${a};`,r=this.replaceCode(`
return ${g};`,[m.start-e.start,m.start-e.start+a.length+7],r,s)}r=this.insertCode(f,A?c:c+1,r,s);let h="";N?h=`const newElem=Blue.r(Comp, attr, ${this.PARAM_ALTER_NAME}.children)`:h="const newElem=Blue.r(Comp, attr)",h=`
${g}.${this.UPDATE_LISTENER_FUNC_NAME} = (Comp, attr) =>{
    ${h}
    ${g}.before(newElem);
    ${g}.remove();
    return newElem
  }
`;let F=!1;for(let a in x){F||(F=!0);let l=x[a];h+=`import.meta.hot.accept('${a}',({${l.varMapCode}})=>{${l.listenCode}});`}return F&&(h=`
if(import.meta.hot){
  ${h}
}else{
  console.warn('import.meta.hot does not exist')
}
`),r=this.insertCode(h,O,r,s),r}resolveFilePath(t,e){let r=_.resolve(e,"../",t);try{let i=C.statSync(r);if(i.isDirectory()){let s=C.readdirSync(r);for(let o=s.length;o--;){let n=s[o];if(/index\.(?:[jt]sx|mdx?)$/.test(n))return t+"/"+n}}else return i.isFile()?t:!1}catch{let s=C.readdirSync(_.resolve(r,"../")),o=_.basename(t),n=_.dirname(t);for(let c=s.length;c--;){let d=s[c];if(s.indexOf(o)===0&&/\.(?:[jt]sx|mdx?)$/.test(d))return n+"/"+d}}return!1}getImports(t,e){let r={varNames:[],info:{}};for(let i of t){if(i.type!=="ImportDeclaration"||i.source.value.indexOf(".")!==0)continue;let s=this.resolveFilePath(i.source.value,e);if(!s)continue;let o={src:s,imports:{}};r.info[i.source.value]=o;for(let n of i.specifiers){let c=n.local.name;n.type==="ImportDefaultSpecifier"?o.imports[c]="default":n.type==="ImportSpecifier"&&(o.imports[c]=n.imported.name),r.varNames.push({name:c,info:o})}}return r}getExports(t){return t.filter(e=>e.type==="ExportDefaultDeclaration"||e.type==="ExportNamedDeclaration")}getExportedFunctions(t){let e=[],r=[],i=(s,o=!1)=>{let{type:n}=s;if(!o&&n==="FunctionDeclaration"||n==="ArrowFunctionExpression")e.push(s);else if(n==="VariableDeclaration")if(o)for(let c of s.declarations)r.includes(c.id.name)&&i(c.init);else for(let c of s.declarations)i(c.init);else n==="Identifier"&&r.push(s.name)};for(let s=t.length;s--;){let o=t[s];if(o.type==="ExportDefaultDeclaration"||o.type==="ExportNamedDeclaration"){let{declaration:n,specifiers:c}=o;n?i(n):c.forEach(d=>{i(d.local)})}else r.length&&i(o,!0)}return e}getDependentJSXComponents(t,e){let r=[];for(let i of t.matchAll(/Blue\.r\(([A-Z][A-z_]*)/g)){let s=i[1],o=this.Parser.parseExpressionAt(t,i.index,{ecmaVersion:"latest",sourceType:"module"});o.type==="SequenceExpression"&&(o=o.expressions.find(n=>n.start===o.start));for(let n of e.varNames)if(n.name===s){let c={name:s,info:n.info,node:o,index:i.index};r.push(c)}}return r}getVars(t,e){return[]}fromDirectReturnToVarReturn(t){return""}getReturnValue(t){return""}};var q=new v;function z({enabled:S}={enabled:!0}){return{name:"vite-plugin-blue-hmr",apply(t,{command:e}){return S&&e==="serve"},transform(t,e){if(!e.includes("node_modules")&&/\.[jt]sx$/.test(e))return q.transform(t,e)}}}export{z as default,q as hmrAdder};
