import{Parser as q}from"acorn";var _=class{constructor(){this.UPDATE_LISTENER_FUNC_NAME="_bjsx_hmr_update";this.PARAM_ALTER_NAME="_blue_insert_params"}transform(t){}getImports(...t){return[]}getExports(...t){return[]}getDependentJSXComponents(t,e){return[]}getFunctions(t){return[]}getVars(t,e){return[]}fromDirectReturnToVarReturn(t){return""}getReturnValue(t){return""}getInsertRecord(){return[]}replaceCode(t,e,r,n,s=!1){let o=0;return n.filter(a=>a[0]<e[0]||s&&a[0]===e[0]).forEach(a=>o+=a[1]),n.push([e[0],t.length-e[1]+e[0]]),r.substring(0,e[0]+o)+t+r.substring(e[1]+o)}insertCode(t,e,r,n,s=!1){return this.replaceCode(t,[e,e],r,n,s)}getCodeFragment(t,e,r){let n=t[0],s=t[1];for(let o=r.length;o--;){let[a,m]=r[o];a<t[1]&&(s+=m,a<t[0]&&(n+=m))}return e.substring(n,s)}};import b from"path";import M from"fs";var S=class extends _{constructor(){super();this.Parser=q}transform(t,e){t=t.replace(/=>/g,"=> ");let r=this.Parser.parse(t,{ecmaVersion:"latest",sourceType:"module"}),n=t,s=this.getImports(r.body,e),o=this.getExportedFunctions(r.body),a=this.getInsertRecord();return o.forEach(m=>{let{start:g,end:h}=m,E=this.getCodeFragment([g,h],t,a),f=this.getDependentJSXComponents(E,s);t=this.replaceCode(this.processFunctionCode(f,m,E,n),[g,h],t,a)}),t}addHotListenerInfo(t,e,r,n){var o,a;(a=t[o=e.info.src])!=null||(t[o]={varMapCode:"",listenCode:""});let s=t[e.info.src];s.varMapCode+=`${e.info.imports[e.name]}:${e.name},`,s.listenCode+=`
if(${r}.${e.refName}.${this.UPDATE_LISTENER_FUNC_NAME}){
  ${r}.${e.refName}=${r}.${e.refName}.${this.UPDATE_LISTENER_FUNC_NAME}(${e.name});
  ${n}
}else{
  import.meta.hot.decline()
}
`}processFunctionCode(t,e,r,n){var L,V,w,H,J,U;let s=this.getInsertRecord(),o=r,a=e.body,m=a.start-e.start,g=a.end-e.start,h=a.body,E=e.params[0],f="";if(E){let i=E.start-e.start,l=E.end-e.start,u=r.substring(i,l);r=this.replaceCode(this.PARAM_ALTER_NAME,[i,l],r,s),f=`
let ${u}=${this.PARAM_ALTER_NAME};`}let p="self",R=[],A={},c,T=0,d=h==null?void 0:h.find(i=>i.type==="ReturnStatement"),$=a.type==="CallExpression"&&((V=(L=a.callee)==null?void 0:L.object)==null?void 0:V.name)==="Blue";if(d)d.argument.type==="Identifier"&&(p=d.argument.name);else if(!$)return o;let X=d&&d.argument.type==="CallExpression"&&((H=(w=d.argument.callee)==null?void 0:w.object)==null?void 0:H.name)==="Blue",C=$?g:d.start-e.start;for(let i of r.matchAll(/Blue\.r\(/g)){let l=this.Parser.parseExpressionAt(r,i.index,{ecmaVersion:"latest",sourceType:"module"});if(l.type==="SequenceExpression"&&(l=l.expressions.find(u=>u.start===l.start)),(l==null?void 0:l.type)==="CallExpression"&&((J=l==null?void 0:l.arguments[1])==null?void 0:J.type)==="ObjectExpression"){let u=(U=l.arguments[1].properties.find(N=>{var x;return((x=N.key)==null?void 0:x.name)==="ref"}))==null?void 0:U.value.elements[0].name;if(u){c=u;break}}}t.forEach(i=>{let l=i.node.arguments[1];if(l.type==="ObjectExpression"){let u=l.properties.find(N=>N.key.name==="ref");if(u){let N="",x=u.value.elements;if(i.refName=x[1].value,i.hasRef=!0,!$){h.forEach(({type:D,start:I,end:B})=>{let v=I-e.start,k=B-e.start,O=o.substring(v,k);D==="ExpressionStatement"&&o.indexOf(i.refName,v)===v&&(N+=`${c}.${O};`)});for(let D of o.matchAll(new RegExp(i.refName,"g")))try{let I=this.Parser.parseExpressionAt(o,D.index,{ecmaVersion:"latest",sourceType:"module"});(I.type==="AssignmentExpression"||I.type==="CallExpression")&&(r=this.insertCode(`${c}.`,D.index,r,s))}catch{}}this.addHotListenerInfo(A,i,c,N)}else i.refName=`bjsxc_${T++}`,i.hasRef=!1,R.push(()=>{r=this.insertCode(`ref:[${c},'${i.refName}'],`,l.start+1,r,s),this.addHotListenerInfo(A,i,c,"")})}else i.refName=`bjsxc_${T++}`,R.push(()=>{r=this.replaceCode(`{ref:[${c},'${i.refName}']}`,[l.start,l.start+4],r,s),this.addHotListenerInfo(A,i,c,"")})}),c||(c="refs",f+=`const ${c}={};`);for(let i=R.length;i--;)R[i]();if($)f=`{${f}const ${p}=`,r=this.insertCode(`
return ${p};}`,a.end,r,s,!0);else if(X){let i=this.getCodeFragment([d.start-e.start+6,d.end-e.start],r,s);f=`${f}
      const ${p}=${i};`,r=this.replaceCode(`
return ${p};`,[d.start-e.start,d.start-e.start+i.length+7],r,s)}r=this.insertCode(f,$?m:m+1,r,s);let y="";E?y=`
${p}.${this.UPDATE_LISTENER_FUNC_NAME} = (Comp) =>{
  const newElem=Comp(${this.PARAM_ALTER_NAME});
  ${p}.before(newElem);
  ${p}.remove();
  return newElem
}
`:y=`
${p}.${this.UPDATE_LISTENER_FUNC_NAME} = (Comp) =>{
  const newElem=Comp();
  ${p}.before(newElem);
  ${p}.remove();
  return newElem
}
`;let P=!1;for(let i in A){P||(P=!0);let l=A[i];y+=`import.meta.hot.accept('${i}',({${l.varMapCode}})=>{${l.listenCode}});`}return P&&(y=`
if(import.meta.hot){
  ${y}
}else{
  console.warn('import.meta.hot not exist')
}
`),r=this.insertCode(y,C,r,s),r}resolveFilePath(t,e){let r=b.resolve(e,"../",t);try{let n=M.statSync(r);if(n.isDirectory()){let s=M.readdirSync(r);for(let o=s.length;o--;){let a=s[o];if(/index\.[jt]sx$/.test(a))return t+"/"+a}}else return n.isFile()?t:!1}catch{let s=M.readdirSync(b.resolve(r,"../")),o=b.basename(t),a=b.dirname(t);for(let m=s.length;m--;){let g=s[m];if(s.indexOf(o)===0&&/\.[jt]sx$/.test(g))return a+"/"+g}}return!1}getImports(t,e){let r={varNames:[],info:{}};return t.forEach(n=>{if(n.type!=="ImportDeclaration"||n.source.value.indexOf(".")!==0)return 0;let s=this.resolveFilePath(n.source.value,e);if(!s)return 0;let o={src:s,imports:{}};r.info[n.source.value]=o,n.specifiers.forEach(a=>{let m=a.local.name;a.type==="ImportDefaultSpecifier"?o.imports[m]="default":a.type==="ImportSpecifier"&&(o.imports[m]=a.imported.name),r.varNames.push({name:m,info:o})})}),r}getExports(t){return t.filter(e=>e.type==="ExportDefaultDeclaration"||e.type==="ExportNamedDeclaration")}getExportedFunctions(t){let e=[],r=n=>{n.type==="FunctionDeclaration"||n.type==="ArrowFunctionExpression"?e.push(n):n.type==="VariableDeclaration"&&n.declarations.forEach(s=>r(s.init))};return t.forEach(n=>{if(n.type==="ExportDefaultDeclaration"||n.type==="ExportNamedDeclaration"){let{declaration:s}=n;s&&r(s)}}),e}getDependentJSXComponents(t,e){let r=[];for(let n of t.matchAll(/Blue\.r\(([A-Z][A-z_]*)/g)){let s=n[1],o=this.Parser.parseExpressionAt(t,n.index,{ecmaVersion:"latest",sourceType:"module"});o.type==="SequenceExpression"&&(o=o.expressions.find(a=>a.start===o.start)),e.varNames.forEach(a=>{if(a.name===s){let m={name:s,info:a.info,node:o,index:n.index};r.push(m)}})}return r}getVars(t,e){return[]}fromDirectReturnToVarReturn(t){return""}getReturnValue(t){return""}};var z=new S;function Z({enabled:F}={enabled:!0}){return{name:"vite-plugin-blue-hmr",apply(t,{command:e}){return F&&e==="serve"},transform(t,e){if(!e.includes("node_modules")&&/\.[jt]sx$/.test(e))return z.transform(t,e)}}}export{Z as default,z as hmrAdder};
